TEMPLATES = {
    "number_one": [
        '"{title}" by {artist} didn\'t just top the charts in {year}—it owned them! {emoji}',
        'Stop everything! In {year}, "{title}" by {artist} took #1 and never looked back. {emoji}',
        '"{title}" by {artist} absolutely crushed it in {year}—charted at #1 and in our memories! {emoji}',
        'Legend status: "{title}" by {artist} was the anthem of {year}, holding the top spot! {emoji}',
        '"{title}"—honestly, what a tune. {artist} at their chart-topping best in {year}. {emoji}',
        'Raise your hands if "{title}" (by {artist}, {year}) is still your karaoke go-to! #1 for a reason. {emoji}',
        'Full disclosure—I still get chills when I hear "{title}". #1 in {year} for {artist}, and in my heart! {emoji}',
        'Plot twist: "{title}" by {artist} was the *actual* national anthem of {year}. Joking… or not? {emoji}',
        '"{title}" was everywhere in {year}! (If you know every lyric by heart, you\'re not alone.) {emoji}',
        'Can you believe "{title}" hit #1 back in {year}? Seriously: it still slaps. {emoji}',
        'I dare you not to sing along! "{title}" by {artist} was the #1 song of {year}. {emoji}',
        '"{title}"—remember rushing to the radio when this hit #1 for {artist} in {year}? {emoji}',
        'Forever iconic: "{title}" at the top in {year}. {emoji} Any {artist} superfans out there?',
    ],
    "top_ten": [
        'Big mood in {year}: "{title}" by {artist}—a well-deserved Top 10! Landed at #{peak_rank}. {emoji}',
        '"{title}" by {artist} lit up the charts in {year}, peaking at #{peak_rank}. Still a banger! {emoji}',
        'Not quite #1, but pretty darn close! "{title}" by {artist} hit #{peak_rank} in {year}. Still in heavy rotation! {emoji}',
        '"{title}" by {artist} cracked the Top 10 in {year}! Anyone else still blast this in the car? {emoji}',
        'Hot take: #{peak_rank} in {year} was too low for "{title}" by {artist}. Deserved even higher! {emoji}',
        'Raise your hand if "{title}" by {artist} is on your playlist. Top 10 in {year}, eternal hit today. {emoji}',
        'Let\'s be real, "{title}" by {artist} should\'ve gone all the way—but Top 10 in {year} isn\'t bad! {emoji}',
        'I still remember dancing to "{title}" by {artist} when it peaked at #{peak_rank} in {year}. What a time. {emoji}',
        '"{title}" by {artist} was one of {year}\'s greatest jams, climbing all the way to #{peak_rank}. {emoji}',
        '"{title}" by {artist}—I vote we give it a retroactive #1. But hey, Top 10 is legendary! {emoji}',
    ],
    "longevity": [
        '"{title}" by {artist} refused to leave the charts—{weeks_on_chart} weeks running! Staying power, folks. {emoji}',
        'How many weeks? {weeks_on_chart}! "{title}" by {artist} just didn\'t quit in {year}. {emoji}',
        'Chart marathon! "{title}" by {artist} stuck around for {weeks_on_chart} weeks—talk about a fan favorite. {emoji}',
        '"{title}" by {artist} hit shuffle and park: {weeks_on_chart} weeks on the Hot 100. Respect. {emoji}',
        'They say good things don\'t last… but "{title}" by {artist} said “Hold my drink” for {weeks_on_chart} weeks! {emoji}',
        'Do you remember a world before "{title}" by {artist}? Probably not—{weeks_on_chart} weeks charting! {emoji}',
        '"{title}" by {artist} was basically the soundtrack of the year. {weeks_on_chart} weeks and still not enough! {emoji}',
        '"{title}" found a spot—and held it! {artist} kept us listening for {weeks_on_chart} weeks. {emoji}',
    ],
    "short_run": [
        'Blink and you missed it! "{title}" by {artist} had a short-but-sweet {weeks_on_chart}-week run in {year} {emoji}',
        'Not every hit stays forever—"{title}" by {artist} was on the charts for just {weeks_on_chart} weeks. Iconic anyway? You bet! {emoji}',
        '"{title}" by {artist}: in and out in {weeks_on_chart} weeks. But hey, sometimes great things come in small, catchy packages! {emoji}',
        '"{title}" by {artist} didn\'t stick around long—just {weeks_on_chart} weeks—but it made a big impression! {emoji}',
        'Every chart needs its quick-fire sparks: enter "{title}" by {artist}. {weeks_on_chart} weeks of glory. {emoji}',
        'Any other fans of blink-and-you-miss-it hits? "{title}" by {artist} stayed for {weeks_on_chart} magical weeks. {emoji}',
    ],
    "timeless": [
        'They just don\'t make them like "{title}" by {artist} anymore—timeless since {year}! {emoji}',
        '"{title}" by {artist} turned {year} into pure pop gold, and it STILL rocks. {emoji}',
        '"{title}" by {artist} has been around more than 50 years and never gets old. Legends only! {emoji}',
        '"{title}" by {artist}—if you know, you know. Some tracks, like this one from {year}, age like fine wine! {emoji}',
        'This isn\'t just a song, it\'s a rite of passage: "{title}" by {artist}, as fresh today as in {year}. {emoji}',
        'Guaranteed to make any playlist better: "{title}", the {year} classic by {artist}. {emoji}',
        'Decades later and still no skip: "{title}" by {artist}. Iconic since {year}! {emoji}',
        'Sometimes I wish I could hear "{title}" by {artist} for the first time again. {year} to now, it never left us. {emoji}',
    ],
    "sixties": [
        '"{title}" by {artist}—they don\'t groove like this anymore! #60sVibes {emoji}',
        'Step back in time to {year}: "{title}" by {artist}, still swinging! {emoji}',
        '"{title}" by {artist} captured the spirit of the sixties with every note. {emoji}',
        'That 60s feeling: "{title}" by {artist}. What a trip! {emoji}',
        '"{title}"—prime sixties energy from {artist} ({year}). Still a party-starter! {emoji}',
        '"{title}" by {artist}: flower power, vinyl crackle, and pure magic from {year}. {emoji}',
    ],
    "seventies": [
        'Disco balls, platform shoes, and "{title}" by {artist}—it all came together in the 70s! {emoji}',
        '"{title}" by {artist} lit up dance floors and radios everywhere in {year}. Groove on, {artist}! {emoji}',
        'Who else still does the hustle to "{title}" by {artist}? Straight outta {year}! {emoji}',
        '"{title}"—a shining star in a decade of classics. {artist} at their 70s peak! {emoji}',
        'The 70s gave us many things, but none better than "{title}" by {artist}. {emoji}',
        'From lava lamps to air guitars: "{title}" by {artist} was the vibe in {year}. {emoji}',
    ],
    "eighties": [
        'Big hair, big synths, big hooks: "{title}" by {artist} is pure 80s magic! {emoji}',
        '"{title}" by {artist} brought the neon to our ears in {year}. Still gets me moving! {emoji}',
        '"{title}" by {artist} feels like a John Hughes montage in song form. Long live the 80s! {emoji}',
        'Turn it up! "{title}" by {artist} was an 80s must-have, courtesy of {artist}. {emoji}',
        'Remember blasting "{title}" in your Walkman? Me too. 80s bliss from {artist}. {emoji}',
    ],
    "nineties": [
        '"{title}" by {artist} made my mixtapes in {year}, and it hasn\'t left since. 90s forever! {emoji}',
        'Relive your best 90s moments with "{title}" by {artist}. All that and a bag of chips! {emoji}',
        'Big chords, feel-good vibes: "{title}" by {artist} defines 90s pop. {artist} nailed it in {year}! {emoji}',
        '"{title}" by {artist}—played endlessly on my boombox. Who else? 90s gold! {emoji}',
        '"{title}" by {artist} is {year} in a nutshell. All the (baggy) feels! {emoji}',
    ],
    "two_thousands": [
        'Is it just me, or does "{title}" by {artist} scream early 2000s nostalgia? {emoji}',
        'Every memory from the 2000s has "{title}" by {artist} in the background. Timeless! {emoji}',
        'Before streaming, there was "{title}"—a {artist} anthem blasting on every radio in {year}. {emoji}',
        '"{title}" by {artist}: instantly takes me back. Anyone else still know every word? {emoji}',
        '"{title}" by {artist} = peak 2000s. IYKYK. {emoji}',
    ]
}

FALLBACK_TEMPLATES = [
    '"{title}" by {artist} scored big in {year}, charting at #{peak_rank}. Still such a jam!',
    'Turn up the memories with "{title}" by {artist}—#{peak_rank} hit in {year}.',
    'Who else still listens to "{title}" by {artist}? That {year} classic peaked at #{peak_rank}.',
    '"{title}" by {artist} reached #{peak_rank} in {year}—and I\'m still obsessed!',
    'Classic alert: "{title}" by {artist}, charted at #{peak_rank} in {year}. Had you forgotten this one?',
    'Your daily reminder: "{title}" by {artist} once dominated the charts at #{peak_rank} in {year}!',
    'If "{title}" by {artist} isn\'t an all-timer, what is? Iconic chart run in {year}.',
]
