TEMPLATES = {
    "number_one": [
        '"{title}" by {artist} didn\'t just top the charts in {year}—it owned them! {emoji}',
        'Chart royalty: "{title}" by {artist} claimed the #1 spot in {year} and never let go. {emoji}',
        '"{title}" by {artist} absolutely dominated {year}—#1 on the charts and in our hearts! {emoji}',
        'Legend status: "{title}" by {artist} was the defining song of {year}. {emoji}',
        '"{title}" by {artist} proved why they deserved that #1 spot in {year}. Pure excellence. {emoji}',
        'Who else remembers when "{title}" by {artist} ruled {year}? #1 for all the right reasons. {emoji}',
        '"{title}" by {artist} wasn\'t just popular—it was essential listening in {year}. {emoji}',
        'Some songs define their era. "{title}" by {artist} owned {year} from the #1 position. {emoji}',
        '"{title}" was everywhere in {year}! We all knew every word for good reason. {emoji}',
        'Chart perfection: "{title}" by {artist} hitting #1 in {year} just made sense. {emoji}',
        'The anthem we all needed: "{title}" by {artist} at #1 throughout {year}. {emoji}',
        'Peak {artist}: "{title}" sitting pretty at #1 and setting the standard in {year}. {emoji}',
        '"{title}" by {artist} wasn\'t just a hit—it was THE moment of {year}. {emoji}',
        'When a song hits #1 and stays there, you know it\'s special. Enter "{title}" by {artist}. {emoji}',
        'Chart history at its finest: "{title}" by {artist} owning the top spot in {year}. {emoji}',
        'The song that had us all singing along: "{title}" by {artist}, #1 in {year}. {emoji}',
        '"{title}" by {artist} didn\'t just reach #1—it redefined what a hit could be. {emoji}',
        'Some artists spend careers chasing #1. {artist} nailed it perfectly with "{title}" in {year}. {emoji}',
        'The gold standard: "{title}" by {artist} showing everyone how it\'s done from #1. {emoji}',
        'Cultural phenomenon alert: "{title}" by {artist} ruling from the top in {year}. {emoji}',
        '"{title}" by {artist} turned {year} into their personal soundtrack. #1 well earned! {emoji}',
        'Master class in hit-making: "{title}" by {artist} at #1 throughout {year}. {emoji}',
        'The song that united us all: "{title}" by {artist}, reigning supreme in {year}. {emoji}',
        'Chart domination at its finest: "{title}" by {artist} making {year} unforgettable. {emoji}',
        'When "{title}" by {artist} hit #1 in {year}, it felt like the perfect soundtrack. {emoji}',
    ],
    
    "top_ten": [
        'Solid gold: "{title}" by {artist} earned that #{peak_rank} spot in {year}! {emoji}',
        '"{title}" by {artist} made serious waves, climbing to #{peak_rank} in {year}. Still fantastic! {emoji}',
        'Top 10 excellence: "{title}" by {artist} peaked at #{peak_rank} and proved why we love great music. {emoji}',
        '"{title}" by {artist} cracked the Top 10 in {year}! Still sounds as fresh as ever. {emoji}',
        'Honestly? #{peak_rank} in {year} feels low for "{title}" by {artist}. Deserved even higher! {emoji}',
        'Chart success story: "{title}" by {artist} climbing to #{peak_rank} in {year}. {emoji}',
        '"{title}" by {artist} showed serious staying power at #{peak_rank} in {year}. {emoji}',
        'Top 10 hit that still hits: "{title}" by {artist} at #{peak_rank} in {year}. {emoji}',
        '"{title}" by {artist} was one of {year}\'s standout tracks, peaking at #{peak_rank}. {emoji}',
        'Quality music right here: "{title}" by {artist} earning that #{peak_rank} position. {emoji}',
        'The Top 10 was lucky to have "{title}" by {artist} at #{peak_rank} in {year}. {emoji}',
        'Chart climber: "{title}" by {artist} working its way to #{peak_rank} in {year}. {emoji}',
        '"{title}" by {artist} at #{peak_rank}—proof that great songs find their audience. {emoji}',
        'Top 10 territory: where "{title}" by {artist} belonged in {year}. #{peak_rank} and counting! {emoji}',
        'The charts got it right: "{title}" by {artist} deserved every bit of that #{peak_rank} spot. {emoji}',
        'Peak performance: "{title}" by {artist} showing what they\'re made of at #{peak_rank}. {emoji}',
        '"{title}" by {artist} reminded us why the Top 10 exists—#{peak_rank} in {year}! {emoji}',
        'Chart magic: "{title}" by {artist} finding its perfect spot at #{peak_rank} in {year}. {emoji}',
        'The #{peak_rank} position suited "{title}" by {artist} perfectly in {year}. {emoji}',
        'Top 10 essential: "{title}" by {artist} at #{peak_rank}, still in our regular rotation. {emoji}',
        '"{title}" by {artist} proved chart success isn\'t luck—#{peak_rank} was well-earned. {emoji}',
        'Quality over quantity: "{title}" by {artist} making #{peak_rank} count in {year}. {emoji}',
        'The Top 10 needed "{title}" by {artist} at #{peak_rank} to be complete. {emoji}',
        'Chart success story: "{title}" by {artist} climbing to #{peak_rank} and staying relevant. {emoji}',
    ],
    
    "longevity": [
        '"{title}" by {artist} had serious staying power—{weeks_on_chart} weeks on the charts! {emoji}',
        'Chart marathon champion: "{title}" by {artist} going strong for {weeks_on_chart} weeks. {emoji}',
        'The definition of a slow burn: "{title}" by {artist} charting for {weeks_on_chart} weeks straight. {emoji}',
        '"{title}" by {artist} knew how to stick around—{weeks_on_chart} weeks of chart success! {emoji}',
        'Longevity goals: "{title}" by {artist} refusing to leave for {weeks_on_chart} weeks. {emoji}',
        'The song that wouldn\'t quit: "{title}" by {artist} charting for {weeks_on_chart} weeks! {emoji}',
        'Talk about staying power! "{title}" by {artist} lived on the charts for {weeks_on_chart} weeks. {emoji}',
        '"{title}" by {artist} understood the assignment: {weeks_on_chart} weeks of pure chart endurance. {emoji}',
        'The long game champion: "{title}" by {artist} charting strong for {weeks_on_chart} weeks. {emoji}',
        'Chart persistence at its finest: "{title}" by {artist} going {weeks_on_chart} weeks strong. {emoji}',
        '"{title}" by {artist} showed us what real staying power looks like—{weeks_on_chart} weeks! {emoji}',
        'The marathon runner of hits: "{title}" by {artist} charting for {weeks_on_chart} weeks. {emoji}',
        'Slow and steady wins: "{title}" by {artist} proving longevity with {weeks_on_chart} weeks. {emoji}',
        '"{title}" by {artist} made the charts their home for {weeks_on_chart} weeks straight. {emoji}',
        'Chart endurance record: "{title}" by {artist} going the distance at {weeks_on_chart} weeks. {emoji}',
        'The gift that kept giving: "{title}" by {artist} charting for {weeks_on_chart} amazing weeks. {emoji}',
    ],
    
    "short_run": [
        'Brief but brilliant: "{title}" by {artist} made {weeks_on_chart} weeks count in {year}. {emoji}',
        'Quality over quantity: "{title}" by {artist} proving great things come in {weeks_on_chart}-week packages. {emoji}',
        '"{title}" by {artist} was chart lightning—{weeks_on_chart} weeks of pure impact. {emoji}',
        'Short and sweet perfection: "{title}" by {artist} making every one of {weeks_on_chart} weeks matter. {emoji}',
        'The quick strike specialist: "{title}" by {artist} dominating for {weeks_on_chart} focused weeks. {emoji}',
        '"{title}" by {artist} proved you don\'t need forever—just {weeks_on_chart} perfect weeks. {emoji}',
        'Chart efficiency: "{title}" by {artist} making maximum impact in {weeks_on_chart} weeks. {emoji}',
        'The shooting star approach: "{title}" by {artist} blazing bright for {weeks_on_chart} weeks. {emoji}',
        '"{title}" by {artist} showed that {weeks_on_chart} weeks can be enough to make history. {emoji}',
        'Concentrated greatness: "{title}" by {artist} packing everything into {weeks_on_chart} weeks. {emoji}',
        'The sprint champion: "{title}" by {artist} maximizing {weeks_on_chart} weeks of chart time. {emoji}',
        '"{title}" by {artist} understood timing—{weeks_on_chart} weeks of perfectly executed impact. {emoji}',
    ],
    
    "timeless": [
        'Still sounds fresh after all these years: "{title}" by {artist} from {year}. {emoji}',
        '"{title}" by {artist} has been soundtrack material since {year}—and counting! {emoji}',
        'The definition of timeless: "{title}" by {artist} aging like fine wine since {year}. {emoji}',
        'Decades later and we\'re still here for "{title}" by {artist}. Classic status confirmed! {emoji}',
        '"{title}" by {artist} proved some songs are built to last—still perfect after 50+ years. {emoji}',
        'Cross-generational appeal: "{title}" by {artist} connecting us all since {year}. {emoji}',
        'The gold standard: "{title}" by {artist} showing what timeless really means since {year}. {emoji}',
        '"{title}" by {artist} from {year} remains as relevant as ever. True artistry! {emoji}',
        'Some songs transcend their era. "{title}" by {artist} has been doing it since {year}. {emoji}',
        'The gift that keeps on giving: "{title}" by {artist} still enriching playlists since {year}. {emoji}',
        'Musical DNA: "{title}" by {artist} woven into our cultural fabric since {year}. {emoji}',
        'The test of time champion: "{title}" by {artist} proving excellence never goes out of style. {emoji}',
        '"{title}" by {artist} isn\'t just old—it\'s essential. Timeless since {year}! {emoji}',
        'Multi-generational masterpiece: "{title}" by {artist} connecting families since {year}. {emoji}',
        'The standard bearer: "{title}" by {artist} setting the bar high since {year}. {emoji}',
    ],
    
    "sixties": [
        '"{title}" by {artist} represents everything we love about {year}. {emoji}',
        'Sixties excellence: "{title}" by {artist} capturing the essence of the decade. {emoji}',
        '"{title}" by {artist} was part of the soundtrack that defined {year}. {emoji}',
        'The spirit of the sixties lives on in "{title}" by {artist}. {emoji}',
        '"{title}" by {artist} embodies what made {year} so special musically. {emoji}',
        'A decade-defining moment: "{title}" by {artist} from the incredible year of {year}. {emoji}',
        '"{title}" by {artist} helped write the musical story of the sixties. {emoji}',
        'Pure sixties artistry: "{title}" by {artist} showing what the decade was all about. {emoji}',
        'The sixties gave us many gifts, including "{title}" by {artist}. {emoji}',
        '"{title}" by {artist} was part of the cultural revolution we call the sixties. {emoji}',
        'Sixties perfection: "{title}" by {artist} representing an incredible era. {emoji}',
        '"{title}" by {artist} proves why the sixties remain so influential. {emoji}',
        'The decade that changed everything: "{title}" by {artist} was there for it all. {emoji}',
        'Sixties sound at its finest: "{title}" by {artist} defining a generation. {emoji}',
    ],
    
    "seventies": [
        'Seventies excellence: "{title}" by {artist} capturing what made the decade special. {emoji}',
        '"{title}" by {artist} was part of the seventies soundtrack we all needed. {emoji}',
        'The decade of discovery: "{title}" by {artist} showing what {year} was all about. {emoji}',
        '"{title}" by {artist} embodies the creative spirit of the seventies. {emoji}',
        'Pure seventies artistry: "{title}" by {artist} defining an unforgettable decade. {emoji}',
        '"{title}" by {artist} helped make the seventies the musical powerhouse it was. {emoji}',
        'The seventies gave us countless classics, including "{title}" by {artist}. {emoji}',
        'Decade-defining sound: "{title}" by {artist} representing seventies excellence. {emoji}',
        '"{title}" by {artist} was part of what made the seventies so culturally rich. {emoji}',
        'The creative explosion that was the seventies: "{title}" by {artist} was right there. {emoji}',
        'Seventies perfection: "{title}" by {artist} showing why the decade endures. {emoji}',
        '"{title}" by {artist} captures everything we love about seventies music. {emoji}',
        'The decade that had it all: "{title}" by {artist} proving the point beautifully. {emoji}',
    ],
    
    "eighties": [
        'Eighties excellence: "{title}" by {artist} representing the decade perfectly. {emoji}',
        '"{title}" by {artist} was pure eighties artistry at its finest. {emoji}',
        'The soundtrack of the eighties included gems like "{title}" by {artist}. {emoji}',
        '"{title}" by {artist} embodies what made the eighties so memorable. {emoji}',
        'Decade-defining sound: "{title}" by {artist} showing eighties creativity. {emoji}',
        '"{title}" by {artist} helped write the musical story of the eighties. {emoji}',
        'The eighties gave us innovation and "{title}" by {artist} was part of it. {emoji}',
        'Pure eighties perfection: "{title}" by {artist} capturing the era\'s essence. {emoji}',
        '"{title}" by {artist} was part of what made the eighties culturally significant. {emoji}',
        'The creative energy of the eighties: "{title}" by {artist} was right in the mix. {emoji}',
        'Eighties artistry at work: "{title}" by {artist} defining a generation. {emoji}',
        '"{title}" by {artist} represents everything we celebrate about eighties music. {emoji}',
        'The decade of bold choices: "{title}" by {artist} fitting right in perfectly. {emoji}',
    ],
    
    "nineties": [
        'Nineties perfection: "{title}" by {artist} defining what the decade was about. {emoji}',
        '"{title}" by {artist} was essential listening throughout the nineties. {emoji}',
        'The soundtrack of the nineties included classics like "{title}" by {artist}. {emoji}',
        '"{title}" by {artist} captures the spirit that made the nineties special. {emoji}',
        'Decade-defining artistry: "{title}" by {artist} representing nineties excellence. {emoji}',
        '"{title}" by {artist} was part of what made the nineties so musically rich. {emoji}',
        'The nineties gave us diversity and "{title}" by {artist} was a perfect example. {emoji}',
        'Pure nineties excellence: "{title}" by {artist} showing the decade\'s range. {emoji}',
        '"{title}" by {artist} helped define what nineties music could be. {emoji}',
        'The creative freedom of the nineties: "{title}" by {artist} embodying it perfectly. {emoji}',
        'Nineties artistry: "{title}" by {artist} proving why we love the decade. {emoji}',
        '"{title}" by {artist} was part of the nineties cultural moment we all experienced. {emoji}',
    ],
    
    "two_thousands": [
        'Early 2000s excellence: "{title}" by {artist} capturing the decade\'s energy. {emoji}',
        '"{title}" by {artist} was essential 2000s listening—and still is! {emoji}',
        'The soundtrack of the 2000s included gems like "{title}" by {artist}. {emoji}',
        '"{title}" by {artist} represents everything we love about 2000s music. {emoji}',
        'Decade-defining sound: "{title}" by {artist} showing 2000s artistry. {emoji}',
        '"{title}" by {artist} was part of what made the 2000s so memorable. {emoji}',
        'The 2000s brought us innovation and "{title}" by {artist} delivered it. {emoji}',
        'Pure 2000s perfection: "{title}" by {artist} capturing the era perfectly. {emoji}',
        '"{title}" by {artist} helped shape what 2000s music became. {emoji}',
        'The digital age soundtrack: "{title}" by {artist} was right there with us. {emoji}',
        '"{title}" by {artist} embodies the creative spirit of the 2000s. {emoji}',
        'New millennium, new sound: "{title}" by {artist} leading the way. {emoji}',
    ]
}

FALLBACK_TEMPLATES = [
    '"{title}" by {artist} made its mark in {year}, charting at #{peak_rank}. Still sounds great!',
    'Chart success story: "{title}" by {artist} reaching #{peak_rank} in {year}.',
    'Who else appreciates "{title}" by {artist}? That {year} classic peaked at #{peak_rank}.',
    '"{title}" by {artist} earned that #{peak_rank} spot in {year}—and our respect!',
    'Classic status: "{title}" by {artist}, charted at #{peak_rank} in {year}. Remember this one?',
    'Daily reminder: "{title}" by {artist} once owned position #{peak_rank} in {year}!',
    'If "{title}" by {artist} isn\'t proof of great songwriting, what is? #{peak_rank} in {year}.',
    'The charts got it right: "{title}" by {artist} deserved that #{peak_rank} position.',
    'Quality music recognition: "{title}" by {artist} climbing to #{peak_rank} in {year}.',
    'Chart excellence: "{title}" by {artist} proving why it hit #{peak_rank} in {year}.',
    '"{title}" by {artist} at #{peak_rank}—{year} was a good year for great music.',
    'Peak performance: "{title}" by {artist} showing what #{peak_rank} looks like.',
    'The #{peak_rank} spot suited "{title}" by {artist} perfectly in {year}.',
    '"{title}" by {artist} reminded us why charts exist—#{peak_rank} well deserved!',
    'Musical excellence: "{title}" by {artist} earning every bit of that #{peak_rank} position.',
]
